---
# Variables available to ALL OSs
username: "{{ ansible_facts['user_id'] }}"
stow_dirs:
  - zsh
  - git
  - spacemacs

spacemacs_repo: "https://github.com/syl20bnr/spacemacs"
spacemacs_dest: "{{ ansible_facts['user_dir'] }}/.emacs.d"
spacemacs_branch: "develop"
