---
- name: Stow dotfiles
  shell: "stow -v -t {{ ansible_facts['user_dir'] }} {{ item }}"
  args:
    # Run stow from the directory where the playbook (setup.yml) is located
    chdir: "{{ playbook_dir }}"
  loop: "{{ stow_dirs }}"
  register: stow_result
  changed_when: "'LINK' in stow_result.stderr"
