---
- name: "Arch Linux: Install System Packages"
  pacman:
    name: "{{ system_packages }}"
    state: present
    update_cache: no
    # update_cache on pacman syncs the db, but state: present
    # ensures we do NOT upgrade packages, only install missing ones.
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes

- name: "Ubuntu: Install System Packages"
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600 # Don't update apt cache if done recently
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: yes

- name: Ensure Zsh is the default shell
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
  become: yes
