---
- name: "Arch Linux: Install System Packages"
  pacman:
    name: "{{ common_system_packages + os_system_packages }}"
    state: present
    update_cache: no
    # ensures we do NOT upgrade packages, only install missing ones.
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes

- name: "Ubuntu: Install System Packages"
  apt:
    name: "{{ common_system_packages + os_system_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: yes

- name: Ensure Zsh is the default shell
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
  become: yes
